### ISSUE TITLE
MELCloud check device state error, AxiosError: Request failed with status code 429

### ISSUE THREAD

**Issue by imTHAI** [grzegorz914/homebridge-melcloud-control#68]
Hello,

First, thank you a lot for your plugin. I discovered it yesterday and installed it, and all my aircon's were in Apple Home at a glance.

But today I see that my homebridge logs are full of errors like those ones: 
```
[2/5/2024, 6:42:23 PM] [melcloudcontrol] Air Conditioner Bureau check device state error, AxiosError: Request failed with status code 429, check again in 65s.
[2/5/2024, 6:42:23 PM] [melcloudcontrol] Air Conditioner Salle de jeu check device state error, AxiosError: Request failed with status code 429, check again in 65s.
[2/5/2024, 6:42:23 PM] [melcloudcontrol] Air Conditioner Chambre Anakin check device state error, AxiosError: Request failed with status code 429, check again in 65s.
[2/5/2024, 6:42:23 PM] [melcloudcontrol] Air Conditioner Chambre parents check device state error, AxiosError: Request failed with status code 429, check again in 65s.
```

And all my aircon were "not answering" in Apple Home.
So l logged into https://app.melcloud.com and it says:

`We have detected excessive traffic from your account, your access to the service has been limited for a few hours.`

So I think the plugin does too many requests or too often. Is it a way to limit it ? Did I miss something ?

For now I've disabled it and will enable it again tomorrow.

**Comment by grzegorz914** [comment]
Yes, the error is to many requests to MELCloud server, I can add possibility to set manually the polling time for state update. In my environment I don't se e this error yet.

**Comment by grzegorz914** [comment]
added in 0.15.0

**Comment by imTHAI** [comment]
That was fast 🤩
Thank you

**Comment by richardalow** [comment]
Thanks for fixing so quickly! I'm waiting too - I hope they don't break the amazing automation you can build with this!

**Comment by grzegorz914** [comment]
Today the account is unlocked and start working correct. I have set device polling time to 90s and account to 150s, will look what happens.

**Comment by richardalow** [comment]
I'm hitting 429 errors again already. It seems it's checking more often than it should e.g.

[06/02/2024, 04:53:34] Air Conditioner Guest Suite  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[06/02/2024, 04:53:35] Air Conditioner Guest Suite  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[06/02/2024, 04:53:48] Air Conditioner Guest Suite  check device state error, AxiosError: Request failed with status code 429, check again in 180s.

**Comment by richardalow** [comment]
Thanks. I created a guest account so I can switch between them until we figure this out.

It seems that when you change the state it kicks off another set of polling. For `Master bedroom`, I turned it off at 08:30 and have the polling set to 300s. You can see polling every 5 minutes from startup and 5 minutes from when I turned it off:

```[06/02/2024, 08:33:33] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:33:34] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {
[06/02/2024, 08:35:02] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:35:03] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {
[06/02/2024, 08:38:34] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:38:35] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {
[06/02/2024, 08:40:03] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:40:04] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {
[06/02/2024, 08:43:36] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:43:37] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {
[06/02/2024, 08:45:04] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:45:05] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {
[06/02/2024, 08:48:37] [melcloudcontrol] Air Conditioner, Master bedroom , debug: Info: {
[06/02/2024, 08:48:38] [melcloudcontrol] Air Conditioner, Master bedroom , debug: State: {```

This will be eating into whatever budget Mitsubishi have set.

**Comment by iceman60** [comment]
Same for me yesterday, blocked account.

> Today the account is unlocked and start working correct. I have set device polling time to 90s and account to 150s, will look what happens.

Does this polling rates resolved the issue ?

Waiting for unlocking right now...

Again thank you a lot for your awesome plugin !

**Comment by richardalow** [comment]
My feeling is we'll need to minimise all calls - so only poll rarely (maybe we need to set it much higher, like 1 hour) and only when necessary (so fixing my comment above). You'd lose recency of the temperatures but, at least on my units, they are pretty far from the actual temperature so not very useful. You'd also take longer to realise someone had manually configured a unit with the remote.

**Comment by grzegorz914** [comment]
For me it's start working today normally, may be this was accidental issue on server side. Will look.

**Comment by mpopof** [comment]
> Today the account is unlocked and start working correct. I have set device polling time to 90s and account to 150s, will look what happens.
> For me it's start working today normally, may be this was accidental issue on server side. Will look.
So the above polling time is working fine for you and you have not experienced another lock?

**Comment by grzegorz914** [comment]
@mpopof 
this setting are working correct for me today, we don't know what a restrictions are set on server side, so need to test it little longer.

**Comment by grzegorz914** [comment]
Can anyone with already locket access to MELCloud post the data form `_Account file`, the file is in /homebridge/melcloud folder. Before post it please remove your credentials data.

**Comment by fcar12** [comment]
I can login in the app but I can't do any action (the app logsoff and throws the error). In the homebridge logs I get the error for the plugin. Here is the contents of the file requested @grzegorz914.

`{
  "ContextKey": "0000",
  "Client": 000000,
  "Terms": 1284,
  "AL": 1,
  "ML": 0,
  "CMI": true,
  "IsStaff": false,
  "CUTF": false,
  "CAA": false,
  "ReceiveCountryNotifications": false,
  "ReceiveAllNotifications": false,
  "CACA": false,
  "CAGA": false,
  "MaximumDevices": 10,
  "ShowDiagnostics": false,
  "Language": 0,
  "Country": 180,
  "RealClient": 0,
  "Name": "John Doe",
  "UseFahrenheit": false,
  "Duration": 525600,
  "Expiry": "2025-02-05T11:51:09.07",
  "CMSC": false,
  "PartnerApplicationVersion": null,
  "EmailSettingsReminderShown": true,
  "EmailUnitErrors": 0,
  "EmailCommsErrors": 0,
  "ChartSeriesHidden": 0,
  "DeletePending": false,
  "Throttle": true,
  "IsImpersonated": false,
  "LanguageCode": "en",
  "CountryName": "Portugal",
  "CurrencySymbol": "€",
  "SupportEmailAddress": null,
  "DateSeperator": "/",
  "TimeSeperator": ":",
  "AtwLogoFile": "ecodan_logo.png",
  "DECCReport": false,
  "CSVReport1min": false,
  "HidePresetPanel": false,
  "EmailSettingsReminderRequired": false,
  "TermsText": null,
  "MapView": false,
  "MapZoom": 21,
  "MapLongitude": 0.0,
  "MapLatitude": 0.0,
  "Throttled": false
}`

**Comment by grzegorz914** [comment]
@fcar12 

thanks, you need wait as here: https://github.com/grzegorz914/homebridge-melcloud-control/issues/68#issuecomment-1928941091 described

**Comment by grzegorz914** [comment]
@all
I have enabled plugin today am 6:00 and my polling time is set to 90s for device and 150s for account. Now  7 hours working without any error. I will report again today later.

**Comment by fcar12** [comment]
> @fcar12
> 
> thanks, you need wait as here: [#68 (comment)](https://github.com/grzegorz914/homebridge-melcloud-control/issues/68#issuecomment-1928941091) described

Already turned off earlier today (just went into the container to get the logs), now just waiting...

**Comment by richardalow** [comment]
It didn't work for me on 180s polling, but I think it depends on the number of units - I have 9. It has been good for almost 5h on 300s polling.

**Comment by ForkoB** [comment]
"accountRefreshInterval": 120 works fine for me with version 0.15.3

**Comment by grzegorz914** [comment]
> It didn't work for me on 180s polling, but I think it depends on the number of units - I have 9. It has been good for almost 5h on 300s polling.

You need first wait to be account unlocked then start the plugin again.

**Comment by richardalow** [comment]
I did, but I got blocked again after 2 hours.

**Comment by mpopof** [comment]
Im currently set at 120s for device and 150s for account, but giving the above comments I will drop them to 90 device and 120 account if you guys dont get locked out again. I was runnint 0.15.2 until 15mins ago no issues so far with 120/150.

**Comment by grzegorz914** [comment]
account refresh time has no matter because account was never locked, locked was only device state check

**Comment by iceman60** [comment]
This settings are not working for me, I have only one unit connected in my home but still locked by the server after couple of hours.

**Comment by grzegorz914** [comment]
After 10 hours still working correct.

**Comment by peibol81** [comment]
With 0.15.3 the problem persist for me.
I downgraded to 0.14.5, wait a few hours and worked again

**Comment by grzegorz914** [comment]
> With 0.15.3 the problem persist for me. I downgraded to 0.14.5, wait a few hours and worked again

Its working because your account was unlocked, You can update to the latest version and set poling time for device to 120 seconds.

**Comment by mafonso** [comment]
Just linking a discussion about a similar problem with another 3rd party integration.  Mitsubishi has allegedly made a decision to crack down on 3rd party integrations, only allowing users to use their (crappy) app. 

https://github.com/home-assistant/core/pull/109750

**Comment by grzegorz914** [comment]
I have just extend possibility to set polling time to 15 min, available right now in 0.15.4

**Comment by grzegorz914** [comment]
12 hours test 90/150, 7 devices still working OK.

**Comment by imTHAI** [comment]
Hello, 
This morning I had set to 120 seconds and I had no problems all day but I notice tonight that I have the message again in the logs. I’ll pass it at 150 seconds and I’ll see tomorrow.
By the way, there are typos or it’s me who is a little lost. In the Air Conditioner tab it is put "Here set the background state refresh time in (sec) for Heat Pump." In the Heat Pump tab it is about ATW device, and in the system tab it's for Air Conditioner. 
So I may not have configured the right place.

**Comment by grzegorz914** [comment]
@imTHAI 
no worries, it's  just typo in UI, will be fixed in the next update

**Comment by iceman60** [comment]
If I was Mitsu and wanted to block unofficial API I will be checking the frequency of API call per user. An automation is requesting the server at fixed time. Do you think they do this? Because on my side the 120/150 refresh is not working.

**Comment by fcar12** [comment]
Maybe that, some headers check or other methods.
https://github.com/home-assistant/core/issues/109728#issuecomment-1930510202

**Comment by mpopof** [comment]
Everything was working fine, until 10 mins ago when I started to get the lockout error. Just stopped the plugin and will increase the polling time back to 120, I have decreased it to 90 earlier today. My account has not been blocked yet.

**Comment by peibol81** [comment]
For me, 150 works fine.
I'm using 0.15.3.

I'm new user here and I would say thank you for all of you. I'm a blind person and I have sone difficulties, but I'm learning fron all of you.
And sorry for my english. Greeting fron Spain!

**Comment by mpopof** [comment]
It had happened again, like 30 mins ago the AC in the living room started throwing errors that i just noticed now, and of course the interface for that AC is blocked hopefully not for long. I have increased the polling time from 120 to 150 and will keep monitoring it. It is super weird how it just works for a while and then all of a sudden starts to throw errors. Anybody else is observing this kind of behaviour?

**Comment by grzegorz914** [comment]
For after 33 hours all working without any error 120/150. Maybe is different based on MELCloud region.

**Comment by iceman60** [comment]
Same for me even at  ata=265/account=150 I'm blocked by the system.

```

{
    "accounts": [
        {
            "language": "7",
            "accountRefreshInterval": 150,
            "ataDisplayMode": 0,
            "ataTemperatureSensor": true,
            "ataPresets": true,
            "ataButtons": [
                {
                    "namePrefix": false
                }
            ],
            "ataRefreshInterval": 265,
            "atwDisplayMode": 0,
            "atwTemperatureSensor": false,
            "atwPresets": false,
            "atwButtons": [
                {
                    "namePrefix": false
                }
            ],
            "atwRefreshInterval": 70,
            "ervDisplayMode": 0,
            "ervTemperatureSensor": false,
            "ervPresets": false,
            "ervButtons": [
                {
                    "namePrefix": false
                }
            ],
            "ervRefreshInterval": 75,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableDebugMode": false,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "platform": "melcloudcontrol"
}

```

**Comment by grzegorz914** [comment]
@iceman60 

please restart plugin and post the data form _Account file, the file is in /homebridge/melcloud folder. Before post it please remove your credentials data.

**Comment by iceman60** [comment]
@grzegorz914 
`{
  "ContextKey": "0-0000000000000-0",
  "Client": 000000,
  "Terms": 1286,
  "AL": 1,
  "ML": 0,
  "CMI": true,
  "IsStaff": false,
  "CUTF": false,
  "CAA": false,
  "ReceiveCountryNotifications": false,
  "ReceiveAllNotifications": false,
  "CACA": false,
  "CAGA": false,
  "MaximumDevices": 10,
  "ShowDiagnostics": false,
  "Language": 7,
  "Country": 78,
  "RealClient": 0,
  "Name": "Mickey Mouse",
  "UseFahrenheit": false,
  "Duration": 525600,
  "Expiry": "2025-02-06T14:36:54.52",
  "CMSC": false,
  "PartnerApplicationVersion": null,
  "EmailSettingsReminderShown": true,
  "EmailUnitErrors": 1,
  "EmailCommsErrors": 1,
  "ChartSeriesHidden": 0,
  "DeletePending": false,
  "Throttle": true,
  "IsImpersonated": false,
  "LanguageCode": "fr",
  "CountryName": "France",
  "CurrencySymbol": "€",
  "SupportEmailAddress": "tech.clim@fra.mee.com",
  "DateSeperator": "/",
  "TimeSeperator": ":",
  "AtwLogoFile": "ecodan_logo.png",
  "DECCReport": false,
  "CSVReport1min": false,
  "HidePresetPanel": false,
  "EmailSettingsReminderRequired": false,
  "TermsText": null,
  "MapView": false,
  "MapZoom": 17,
  "MapLongitude": 0,
  "MapLatitude": 0,
  "Throttled": false
}`

**Comment by mpopof** [comment]
here is mine as well if you need it.

"ContextKey": "0-0000000000000-0",
  "Client": 000000,
  "Terms": 1284,
  "AL": 1,
  "ML": 0,
  "CMI": true,
  "IsStaff": false,
  "CUTF": false,
  "CAA": false,
  "ReceiveCountryNotifications": false,
  "ReceiveAllNotifications": false,
  "CACA": false,
  "CAGA": false,
  "MaximumDevices": 10,
  "ShowDiagnostics": false,
  "Language": 0,
  "Country": 37,
  "RealClient": 0,
  "Name": "Jon Doe",
  "UseFahrenheit": false,
  "Duration": 525600,
  "Expiry": "2025-02-06T09:13:41.117",
  "CMSC": false,
  "PartnerApplicationVersion": null,
  "EmailSettingsReminderShown": true,
  "EmailUnitErrors": 1,
  "EmailCommsErrors": 1,
  "ChartSeriesHidden": 0,
  "DeletePending": false,
  "Throttle": true,
  "IsImpersonated": false,
  "LanguageCode": "en",
  "CountryName": "Bulgaria",
  "CurrencySymbol": "??",
  "SupportEmailAddress": "sofia@climacom.com",
  "DateSeperator": "/",
  "TimeSeperator": ":",
  "AtwLogoFile": "ecodan_logo.png",
  "DECCReport": false,
  "CSVReport1min": false,
  "HidePresetPanel": false,
  "EmailSettingsReminderRequired": false
  "TermsText": null,
  "MapView": false,
  "MapZoom": 20,
  "MapLongitude": 25.396855809376575,
  "MapLatitude": 42.62045816560535,
  "Throttled": false

**Comment by mpopof** [comment]
Here is mine in case it will help

"ContextKey": "0-0000000000000-0",
  "Client": 000000,
  "Terms": 1284,
  "AL": 1,
  "ML": 0,
  "CMI": true,
  "IsStaff": false,
  "CUTF": false,
  "CAA": false,
  "ReceiveCountryNotifications": false,
  "ReceiveAllNotifications": false,
  "CACA": false,
  "CAGA": false,
  "MaximumDevices": 10,
  "ShowDiagnostics": false,
  "Language": 0,
  "Country": 37,
  "RealClient": 0,
  "Name": "Jon Doe",
  "UseFahrenheit": false,
  "Duration": 525600,
  "Expiry": "2025-02-06T09:13:41.117",
  "CMSC": false,
  "PartnerApplicationVersion": null,
  "EmailSettingsReminderShown": true,
  "EmailUnitErrors": 1,
  "EmailCommsErrors": 1,
  "ChartSeriesHidden": 0,
  "DeletePending": false,
  "Throttle": true,
  "IsImpersonated": false,
  "LanguageCode": "en",
  "CountryName": "Bulgaria",
  "CurrencySymbol": "??",
  "SupportEmailAddress": "sofia@climacom.com",
  "DateSeperator": "/",
  "TimeSeperator": ":",
  "AtwLogoFile": "ecodan_logo.png",
  "DECCReport": false,
  "CSVReport1min": false,
  "HidePresetPanel": false,
  "EmailSettingsReminderRequired": false
  "TermsText": null,
  "MapView": false,
  "MapZoom": 20,
  "MapLongitude": 0,
  "MapLatitude": 0,
  "Throttled": false

**Comment by grzegorz914** [comment]
Very strange, only check device state is locked, the account not. What have you in log after restart plugin?

**Comment by iceman60** [comment]
```[2/7/2024, 2:36:53 PM] [homebridge-melcloud-control] Launched child bridge with PID 146616
[2/7/2024, 2:36:54 PM] Registering platform 'homebridge-melcloud-control.melcloudcontrol'
[2/7/2024, 2:36:54 PM] [homebridge-melcloud-control] Loaded homebridge-melcloud-control v0.15.4 child bridge successfully
[2/7/2024, 2:36:54 PM] Loaded 0 cached accessories from cachedAccessories.0E10BC57EAB3.
[2/7/2024, 2:36:54 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-melcloud-control) is running on port 34070.
[2/7/2024, 2:36:55 PM] [homebridge-melcloud-control] ---- Air Conditioner: Salon ----
[2/7/2024, 2:36:55 PM] [homebridge-melcloud-control] Account: 
[2/7/2024, 2:36:55 PM] [homebridge-melcloud-control] Serial:
[2/7/2024, 2:36:55 PM] [homebridge-melcloud-control] Firmware: 37000
[2/7/2024, 2:36:55 PM] [homebridge-melcloud-control] Manufacturer: Mitsubishi
[2/7/2024, 2:36:55 PM] [homebridge-melcloud-control] ----------------------------------
[2/7/2024, 2:36:56 PM] [homebridge-melcloud-control] Air Conditioner Salon check device state error, AxiosError: Request failed with status code 429, check again in 265s.
[2/7/2024, 2:41:22 PM] [homebridge-melcloud-control] Air Conditioner Salon check device state error, AxiosError: Request failed with status code 429, check again in 265s.
[2/7/2024, 2:45:48 PM] [homebridge-melcloud-control] Air Conditioner Salon check device state error, AxiosError: Request failed with status code 429, check again in 265s.
[2/7/2024, 2:50:14 PM] [homebridge-melcloud-control] Air Conditioner Salon check device state error, AxiosError: Request failed with status code 429, check again in 265s.```

**Comment by grzegorz914** [comment]
can you try 0.15.5-beta.0 and let me know

**Comment by iceman60** [comment]
Lets do this :
`[2/7/2024, 2:59:46 PM] [homebridge-melcloud-control] Air Conditioner Salon check device state error, TypeError: Cannot read properties of undefined (reading 'EffectiveFlags'), check again in 265s.`

**Comment by iceman60** [comment]
1. I'm actually locked
2. I was not running a child bridge until now. Will see if its better
3. I have 3 HK automation with the device. I just disabled everything. Should not be a problem ?

**Comment by mpopof** [comment]
Is this solely for @iceman60 iceman60 or do you want me test it as well. @grzegorz914 ? Only one of my two AC's is blocked, hopefully not for long. The plugin is currently stopped

**Comment by grzegorz914** [comment]
try 0.15.5-beta.4 and let me know

**Comment by iceman60** [comment]
It's working now !
Even if my account is still locked in the MELCloud app !

Very strange the log is showing that the process executed multiple time the same command at launch then I manually triggered a preset.

```[2/7/2024, 3:19:56 PM] [Homebridge UI] Running Command: npm install --save homebridge-melcloud-control@0.15.5-beta.4
[2/7/2024, 3:20:28 PM] [homebridge-melcloud-control] Starting child bridge...
[2/7/2024, 3:20:28 PM] [homebridge-melcloud-control] Launched child bridge with PID 153104
[2/7/2024, 3:20:29 PM] Registering platform 'homebridge-melcloud-control.melcloudcontrol'
[2/7/2024, 3:20:29 PM] [homebridge-melcloud-control] Loaded homebridge-melcloud-control v0.15.5-beta.4 child bridge successfully
[2/7/2024, 3:20:29 PM] Loaded 0 cached accessories from cachedAccessories.0E10BC57EAB3.
[2/7/2024, 3:20:29 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-melcloud-control) is running on port 34070.
[2/7/2024, 3:20:30 PM] [homebridge-melcloud-control] ---- Air Conditioner: Salon ----
[2/7/2024, 3:20:30 PM] [homebridge-melcloud-control] Account: 
[2/7/2024, 3:20:30 PM] [homebridge-melcloud-control] Serial: 
[2/7/2024, 3:20:30 PM] [homebridge-melcloud-control] Firmware: 37000
[2/7/2024, 3:20:30 PM] [homebridge-melcloud-control] Manufacturer: Mitsubishi
[2/7/2024, 3:20:30 PM] [homebridge-melcloud-control] ----------------------------------
[2/7/2024, 3:20:31 PM] Salon CEC8 is running on port 38959.
[2/7/2024, 3:20:31 PM] Please add [Salon CEC8] manually in Home app. Setup Code: 
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:20:32 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:20:33 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:20:39 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:20:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:21:12 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:22:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Set: Chaud Conf 19```

**Comment by grzegorz914** [comment]
beta.5 ready to test

**Comment by mpopof** [comment]
it is working for me as well, just installed beta.6 it looks good. Should I keep the polling time to 150 or can I try to go lower?

**Comment by grzegorz914** [comment]
try lower value too

**Comment by iceman60** [comment]
One strange thing with the beta 5 is that the temperature is locked to 17.5°C...
Installing the Beta 6 right now

**Comment by iceman60** [comment]
The temperature is working fine with the beta 6 but why so many call at launch ?

```
[2/7/2024, 3:36:15 PM] [homebridge-melcloud-control] Loaded homebridge-melcloud-control v0.15.5-beta.6 child bridge successfully
[2/7/2024, 3:36:15 PM] Loaded 0 cached accessories from cachedAccessories.0E10BC57EAB3.
[2/7/2024, 3:36:15 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-melcloud-control) is running on port 34070.
[2/7/2024, 3:36:16 PM] [homebridge-melcloud-control] ---- Air Conditioner: Salon ----
[2/7/2024, 3:36:16 PM] [homebridge-melcloud-control] Account: 
[2/7/2024, 3:36:16 PM] [homebridge-melcloud-control] Serial:
[2/7/2024, 3:36:16 PM] [homebridge-melcloud-control] Firmware:
[2/7/2024, 3:36:16 PM] [homebridge-melcloud-control] Manufacturer: Mitsubishi
[2/7/2024, 3:36:16 PM] [homebridge-melcloud-control] ----------------------------------
[2/7/2024, 3:36:17 PM] Salon CEC8 is running on port 35617.
[2/7/2024, 3:36:17 PM] Please add [Salon CEC8] manually in Home app. Setup Code: 
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:36:18 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:36:54 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:36:58 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:37:10 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:37:20 PM] [homebridge-melcloud-control] Air Conditioner Salon Set: Chaud Conf 19 -- Setting the temperature to 19°C with a preset
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: AUTO
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 19°C
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 19°C
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:37:35 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
```

**Comment by grzegorz914** [comment]
no worries, its experimental beta the multi call is irrelevant now

**Comment by iceman60** [comment]
Again the temperature is automatically set and locked to 17.5°C :
```
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:57:22 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:57:42 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:57:43 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Power: ON
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Operation mode: HEATING
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Room temperature: 18°C
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Fan speed mode: WEAK
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Vane swing mode: AUTO
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Heating threshold temperature: 17.5°C
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Cooling threshold temperature: 17.5°C
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Lock physical controls: UNLOCKED
[2/7/2024, 3:57:46 PM] [homebridge-melcloud-control] Air Conditioner Salon Temperature display unit: °C
```

**Comment by RikBast** [comment]
The whole time my MSZ-AP35-VGK did get the too many traffic message in the official app. My other 2 AC (MSZ-HR50VF, MSZ-HR35VF) were ok after a few hours of that too many traffic message. After resetting the WiFi module of the MSZ-AP35-VGK I can use the official app again. Did not activated the plug-in yet.

**Comment by grzegorz914** [comment]
after set refresh data to 60 im locked today too, will change to 120 and test.

**Comment by mpopof** [comment]
Im using the latest beta, with 90/120 device/account and havent had a problem since installing the beta4 and my living room AC was locked for a lil bit.

**Comment by grunchy99** [comment]
I'm using latest beta, pooling 180/300, account blocked again today... But the plugin seems to not respect the pooling timing, look the timestamp and the check again in 180s ! If the plugin check each second, it's normal that Melcoud API lock our account...

[2/8/2024, 8:45:29 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[2/8/2024, 8:45:29 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[2/8/2024, 8:45:40 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[2/8/2024, 8:46:37 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[2/8/2024, 8:46:37 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[2/8/2024, 8:46:37 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.
[2/8/2024, 8:46:37 AM] [homebridge-melcloud-control] Air Conditioner  check device state error, AxiosError: Request failed with status code 429, check again in 180s.

**Comment by grunchy99** [comment]
No, I have just 1 device… yesterday with pooling 120/300 my account was lock after more than 15 hours.

**Comment by grunchy99** [comment]
I will, as soon as my account is unlocked…

**Comment by starec007** [comment]
It still doesn't work for me even though I set the intervals to the highest values.

**Comment by RikBast** [comment]
You could try a 'soft' reset of the WiFi adapter, it worked for me with one of the units which was being blocked all the time. So short push of the reset button, 2 seconds.

**Comment by starec007** [comment]
I think the wifi adapter has nothing to do with this problem. The problem is frequent login to the MELcloud account.

**Comment by grunchy99** [comment]
I think there's a problem with the plugin...

Melcloud use www2.melcloud.com to communicate, resolved by 3 @IP :

;; ANSWER SECTION:
www2.melcloud.com.	60	IN	A	52.17.130.213
www2.melcloud.com.	60	IN	A	54.76.174.250
www2.melcloud.com.	60	IN	A	54.171.134.38

When I trace connection to these 3 @IP, I can see 2 https request per second... So I think this is the source of account blocking ;-) 

tcpdump -i eth0 dst 52.17.130.213 or dst 54.76.174.250 or dst 54.171.134.38
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
15:14:41.506743 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1744315509, win 501, options [nop,nop,TS val 3345934886 ecr 95775856], length 0
15:14:41.794822 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 61720558, win 501, options [nop,nop,TS val 2703461074 ecr 1286039704], length 0
15:14:42.530734 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345935910 ecr 95776913], length 0
15:14:42.818811 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703462098 ecr 1286040728], length 0
15:14:43.554755 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345936934 ecr 95777937], length 0
15:14:43.842792 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703463122 ecr 1286041752], length 0
15:14:44.578755 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345937958 ecr 95778958], length 0
15:14:44.866730 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703464146 ecr 1286042776], length 0
15:14:45.602784 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345938982 ecr 95779982], length 0
15:14:45.890781 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703465170 ecr 1286043800], length 0
15:14:46.626738 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345940006 ecr 95781009], length 0
15:14:46.914742 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703466194 ecr 1286044824], length 0
15:14:47.650728 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345941030 ecr 95782030], length 0
15:14:47.938789 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703467218 ecr 1286045848], length 0
15:14:48.674751 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345942054 ecr 95783054], length 0
15:14:48.962741 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703468242 ecr 1286046872], length 0
15:14:49.698752 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345943078 ecr 95784078], length 0
15:14:49.986793 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703469266 ecr 1286047896], length 0
15:14:50.722787 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345944102 ecr 95785102], length 0
15:14:51.010760 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703470290 ecr 1286048920], length 0
15:14:51.746766 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345945126 ecr 95786126], length 0
15:14:52.034798 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703471314 ecr 1286049945], length 0
15:14:52.770741 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345946150 ecr 95787150], length 0
15:14:53.058732 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703472338 ecr 1286050968], length 0
15:14:53.794738 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345947174 ecr 95788174], length 0
15:14:54.082778 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703473362 ecr 1286051992], length 0
15:14:54.818734 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345948198 ecr 95789198], length 0
15:14:55.106725 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703474386 ecr 1286053016], length 0
15:14:55.842808 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345949222 ecr 95790222], length 0
15:14:56.130805 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703475410 ecr 1286054040], length 0
15:14:56.866750 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345950246 ecr 95791246], length 0
15:14:57.154741 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703476434 ecr 1286055064], length 0
15:14:57.890751 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345951270 ecr 95792270], length 0
15:14:58.178765 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703477458 ecr 1286056088], length 0
15:14:58.914733 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345952294 ecr 95793294], length 0
15:14:59.202732 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703478482 ecr 1286057114], length 0
15:14:59.938741 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345953318 ecr 95794321], length 0
15:15:00.226769 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703479506 ecr 1286058136], length 0
15:15:00.962797 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345954342 ecr 95795342], length 0
15:15:01.250816 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703480530 ecr 1286059162], length 0
15:15:01.986726 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345955366 ecr 95796366], length 0
15:15:02.274817 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703481554 ecr 1286060184], length 0
15:15:03.010729 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345956390 ecr 95797390], length 0
15:15:03.298730 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703482578 ecr 1286061208], length 0
15:15:04.038740 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345957418 ecr 95798414], length 0
15:15:04.326762 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703483606 ecr 1286062232], length 0
15:15:05.070741 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345958450 ecr 95799446], length 0
15:15:05.346755 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703484626 ecr 1286063260], length 0
15:15:06.098755 IP black-pearl.lan.48418 > ec2-52-17-130-213.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 3345959478 ecr 95800478], length 0
15:15:06.370766 IP black-pearl.lan.38036 > ec2-54-76-174-250.eu-west-1.compute.amazonaws.com.https: Flags [.], ack 1, win 501, options [nop,nop,TS val 2703485650 ecr 1286064280], length 0

**Comment by grunchy99** [comment]
If I stop the plugin, connections stop immediately, so the plugin is really the source of these connections.

**Comment by grzegorz914** [comment]
Yes, if You stop plugin the connection stops, why not? You don't need make any trace, just enable debug mode then you see every poll. I don't know why you get 2 parallels connection and call.

**Comment by starec007** [comment]
Will it be solved somehow? Because the plugin cannot be used this way.

**Comment by mpopof** [comment]
quick update from me, its been 5 or so hours since my last post. Still dont have any issues 90/120 polling time, the app is still accessible for both AC's

**Comment by starec007** [comment]
I have set the refresh interval to 900 since yesterday and today it turned off. So the problem is still there.

**Comment by starec007** [comment]
I've had it set up exactly like this since yesterday and I'm disabled in the web interface.

**Comment by grzegorz914** [comment]
In release app we have two refresh intervals, one is for device refresh and one for system refresh, I suggest to set 120 for device and 150 for system.
If You already test latest beta we have also 2 refresh time but the for device is irrelevant here can you set 1 second or more because is local poll, only for system should be set to 120 or more.

**Comment by grzegorz914** [comment]
@grunchy99  please check beta.21 and let me know about the call trace

**Comment by grunchy99** [comment]
It seems to be getting better, more connection every second. I set the timing as you asked, so 120/150. The timing is respected in the debug log and the tcpdump trace is in sync with the debug information. It remains to be confirmed if the account is no longer locked after 12 or 24 hours
​

**Comment by mpopof** [comment]
I just want to give an update. Its been 36+ hours with no account lock, updated to the latest beta last night. These 3 errors are the only ones that came up in the last 36+ hours.

> `[09/02/2024, 02:06:44] [homebridge-melcloud-control] Account Slavyanska2, check devices list error, AxiosError: timeout of 15000ms exceeded, check again in 120s.
>[09/02/2024, 02:08:59] [homebridge-melcloud-control] Account Slavyanska2, check devices list error, AxiosError: timeout of 15000ms exceeded, check again in 120s.
>[09/02/2024, 02:11:14] [homebridge-melcloud-control] Account Slavyanska2, check devices list error, AxiosError: timeout of 15000ms exceeded, check again in 120s.`

Just one weird thing that Im kind of sure is not related, but want to mention it is that the AC didnt start when it was programmed to do in the morning. Ill keep you posted if anything come up.

**Comment by grzegorz914** [comment]
Latest beta 32 contain final changes, now is only possible to set system refresh time, all other for ATA, ATW, ERW settings arte removed. The call trace is drastically reduce, on my side is working without account lock over 36 hours, so I think all will be OK now. Please all to report any problems, if all pass then tomorrow will release 0.16.0 public.

**Comment by starec007** [comment]
Everything seems to be fine. After installing the beta, the whole day today is without a problem with the application.

**Comment by ams158** [comment]
Hi, I found this same issue, I've installed the last beta version and the login error doesn't appear anymore, but still getting the not device found error.

[homebridge-melcloud-control.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14228765/homebridge-melcloud-control.log.txt)

I attach my plugin logs.

**Comment by Lechucico** [comment]
Hello, I've disabled the plugin for 48h and after enabling again here is the same error:

```
[10/02/2024, 11:06:25] [melcloudcontrol] Air Conditioner Sala de estar No device found.
[10/02/2024, 11:06:55] [melcloudcontrol] Air Conditioner Despacho No device found.
[10/02/2024, 11:06:55] [melcloudcontrol] Air Conditioner Pasillo No device found.
```

Logs here: [logs.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14228854/logs.txt)

**Comment by grzegorz914** [comment]
fixed in beta.38

**Comment by Kirshley1** [comment]
With the beta.38 version the device appears in homebridge (previously it showed device not found) but although it appears in homebridge, it does not appear in the Home app on the iPhone. Any idea what is happening?

**Comment by grzegorz914** [comment]
You need add it to home app, go to wiki

**Comment by Kirshley1** [comment]
I have tried to do what it says in the wiki, but the problem is that I can't get the device to add it. I click on the Home icon, add device, more options and it doesn't show me the option to add it anyway. It's strange because in Homebridge it does come out

**Comment by grzegorz914** [comment]
@Kirshley1  post the debug log please.

**Comment by Kirshley1** [comment]
How can I do that?

**Comment by grzegorz914** [comment]
Plugin Settings >> Advanced Settings >> System >> Debug, enable it restart plugin and get the log.

**Comment by Kirshley1** [comment]
I can't find the option within the plugin...the fact is that the first time I had no problems adding the air. Thank you very much anyway.

**Comment by grzegorz914** [comment]
@Kirshley1 
<img width="782" alt="Zrzut ekranu 2024-02-10 o 17 35 34" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/17c6b7d0-b14b-424a-a158-67fc0dcfdbda">

**Comment by grzegorz914** [comment]
@Kirshley1 
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by Kirshley1** [comment]
here is the log. I'm going to the car to drive and in a while I'll look at what you sent me about troubleshooting. thank you so much
[homebridge-melcloud-control.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14229925/homebridge-melcloud-control.log.txt)

**Comment by grzegorz914** [comment]
@Kirshley1  all is correct in the log, use troubleshooting guide or try to change name of AC device.

**Comment by Kirshley1** [comment]
Is it necessary to configure the plugin as a child bridge? I could swear that when it worked for me, I installed it without putting it as a bridge son

**Comment by grzegorz914** [comment]
0.16.0 released, recommended time refresh 120 seconds
